### ISSUE TITLE
Metadata: Suggestion to hold an "Example Code"

### ISSUE THREAD

**Issue by camfindlay** [thoughtfulbloke/NZdataExamples#3]
Current "Example URL" might allow a link to a working version of software (the end result of writing the code). We might also want to direct users to where that can also view the code if it is open source.

Suggesting an "Example Code" as the human readable property for this.

**Comment by camfindlay** [comment]
"Example Code" could be optional if you're only referencing a github repo you can use Example URL.

**Comment by thoughtfulbloke** [comment]
I'm going to mull over this one another day or so to see what other approaches occur, this is generalising the categories I had put in for tutorial material (so examples with code) to include products/sites based on NZ data.

Now, this makes sense for finding out what people have done with data as inspiration, I just want to have a think about the Example vs. Code distinction

**Comment by camfindlay** [comment]
No worries, I figure that's why we dialogue out the details here and fork to data-govt-nz once we have a working model.

Figure you might have a data visualisation for example, you'd want to direct the user to the data vis itself and you might also want to share the code used to create it. So I can see a case for 2 properties.

**Comment by thoughtfulbloke** [comment]
I think it might make more sense for 

Data Description: 
Data URL: 
Data Licence: 
Example Title:
Example Description:
Example Code URL: 
Example Code Licence: 
Example Product URL:
Example Software: 
Author Contact: 

Because what we seem to be describing is finished artefacts/products vs the information on how to make them. I prefer Example Product URL to Example URL because it doesn't equate the product (graph etc) with the full Example, instead making it a component of the example.

**Comment by camfindlay** [comment]
Seems reasonable to me. Add to your working example and close the issue :)
